/**
 * The names the rest of the app uses for database rows and enums.
 *
 * `lib/types/supabase.ts` is machine-generated by `npm run gen:types` and is
 * overwritten wholesale every time it runs. Nothing hand-written may live
 * there. This file is the hand-written half, and it is the one everything
 * imports — `@/lib/types/database` — so a regeneration is invisible to callers.
 *
 * (These aliases used to sit at the foot of the generated file. A regeneration
 * deleted them and broke thirty imports at once. Hence the split.)
 */

import type { Database as Generated } from "./supabase";
import type {
  PendingEnums,
  PendingFunctions,
  PendingTables,
} from "./schema-pending";

export type { Json } from "./supabase";
export type { JoinRequestStatus } from "./schema-pending";

/**
 * The generated schema with the migrations `gen:types` has not seen merged in.
 *
 * `lib/types/schema-pending.ts` says which those are and when to delete it.
 * Everything in the app — the three Supabase clients included — is typed
 * against this, so a table added by a written-but-unpushed migration is a
 * compile error away from being used correctly rather than an `any`.
 */
export type Database = Omit<Generated, "public"> & {
  public: Omit<Generated["public"], "Tables" | "Enums" | "Functions"> & {
    Tables: PendingTables;
    Enums: PendingEnums;
    Functions: PendingFunctions;
  };
};

type Tables = Database["public"]["Tables"];
type Enums = Database["public"]["Enums"];

// --- identity, house, rooms -------------------------------------------------
export type UserRow = Tables["users"]["Row"];
export type HouseRow = Tables["houses"]["Row"];
export type HouseSettingsRow = Tables["house_settings"]["Row"];
export type HouseMemberRow = Tables["house_members"]["Row"];
export type RoomRow = Tables["rooms"]["Row"];
export type RoomAssignmentRow = Tables["room_assignments"]["Row"];
export type InvitationRow = Tables["invitations"]["Row"];
export type JoinRequestRow = Tables["join_requests"]["Row"];

// --- money ------------------------------------------------------------------
export type ExpenseCategoryRow = Tables["expense_categories"]["Row"];
export type ExpenseRow = Tables["expenses"]["Row"];
export type ExpenseSplitRow = Tables["expense_splits"]["Row"];
export type RecurringExpenseRow = Tables["recurring_expenses"]["Row"];
export type MonthlyPeriodRow = Tables["monthly_periods"]["Row"];
export type MemberPeriodBalanceRow = Tables["member_period_balances"]["Row"];
export type SettlementRow = Tables["settlements"]["Row"];
export type ChorePenaltyRow = Tables["chore_penalties"]["Row"];

// --- chores and effort ------------------------------------------------------
export type ChoreTemplateRow = Tables["chore_templates"]["Row"];
export type ChoreAssignmentRow = Tables["chore_assignments"]["Row"];
export type ChoreAssignmentInsert = Tables["chore_assignments"]["Insert"];
export type ScheduleRunRow = Tables["schedule_runs"]["Row"];
export type EffortLedgerRow = Tables["effort_ledger"]["Row"];
export type SwapRequestRow = Tables["swap_requests"]["Row"];

// --- availability and guests ------------------------------------------------
export type MemberAvailabilityRow = Tables["member_availability"]["Row"];
export type AvailabilityExceptionRow = Tables["availability_exceptions"]["Row"];
export type GuestRow = Tables["guests"]["Row"];

// --- notifications ----------------------------------------------------------
export type NotificationRow = Tables["notifications"]["Row"];
export type NotificationPrefsRow = Tables["notification_prefs"]["Row"];
export type NotificationTypeRow = Tables["notification_types"]["Row"];
export type PushSubscriptionRow = Tables["push_subscriptions"]["Row"];

// --- enums ------------------------------------------------------------------
export type HomeType = Enums["home_type"];
export type MemberKind = Enums["member_kind"];
export type MoneyMode = Enums["money_mode"];
export type EffortMode = Enums["effort_mode"];
export type MemberRole = Enums["member_role"];
export type MemberStatus = Enums["member_status"];
export type ResidencyType = Enums["residency_type"];
export type SplitBasis = Enums["split_basis"];
export type ExpenseStatus = Enums["expense_status"];
export type PeriodStatus = Enums["period_status"];
export type SettlementStatus = Enums["settlement_status"];
export type AssignmentStatus = Enums["assignment_status"];
export type AssignmentSource = Enums["assignment_source"];
export type ChoreCategory = Enums["chore_category"];
export type ChoreSlot = Enums["chore_slot"];
export type ChoreScope = Enums["chore_scope"];
export type ChoreFrequency = Enums["chore_frequency"];
export type ExceptionType = Enums["exception_type"];
export type SwapStatus = Enums["swap_status"];
export type NotifyChannel = Enums["notify_channel"];
