import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { ApiError } from "@/lib/api/errors";
import { route } from "@/lib/api/handler";
import { getHouseContext, requireSession } from "@/lib/data/house";
import { getSettlementForPeriod, type SettlementStatement } from "@/lib/data/settlement";
import { insightPeriodSchema } from "@/lib/validation/insights";
import { paiseToRupeeString } from "@/lib/utils/money";

/**
 * GET /api/insights/statement/2026-08 — the PDF settlement statement (IN-10).
 *
 * Issued only for a closed month: a statement of a month the house can still
 * change is not a statement.
 *
 * The document is deliberately plain. Standard Helvetica embeds no font file,
 * which keeps the response small and needs no asset pipeline — but it is
 * Latin-1 only, so every string is transliterated before it is drawn. A name
 * pdf-lib cannot encode throws at draw time, which would turn one member's
 * name into a 500 for the whole Home.
 *
 * For the same reason amounts are written as `Rs.` rather than `₹`: the rupee
 * sign is not in Helvetica's encoding.
 */

const A4: [number, number] = [595.28, 841.89];
const MARGIN = 50;
const LINE = 18;

export const GET = route(
  async (request: Request, { params }: { params: Promise<{ period: string }> }) => {
    const session = await requireSession();
    const context = await getHouseContext(session);

    const period = insightPeriodSchema.parse((await params).period);
    const statement = await getSettlementForPeriod(session, context.house.id, period);

    if (!statement) {
      throw new ApiError(
        "NOT_FOUND",
        { period },
        "There is no statement for that month yet — a statement is issued once the month is closed.",
      );
    }

    const pdf = await render(statement, context.house.name);

    return new NextResponse(Buffer.from(pdf), {
      status: 200,
      headers: {
        "content-type": "application/pdf",
        "content-disposition": `attachment; filename="houseos-statement-${period}.pdf"`,
        "cache-control": "no-store",
      },
    });
  },
);

/**
 * Helvetica's WinAnsi encoding covers Latin-1 and nothing else, and pdf-lib
 * throws rather than substituting. A Home whose members write their names in
 * Tamil or Devanagari would otherwise get a 500 instead of a statement, so
 * anything outside the encoding becomes a question mark and the row still
 * prints.
 */
function encodable(value: string): string {
  return [...value].map((character) => (character.charCodeAt(0) < 256 ? character : "?")).join("");
}

function money(paise: number): string {
  return `Rs. ${paiseToRupeeString(paise)}`;
}

class Sheet {
  private page: PDFPage;
  private y: number;

  constructor(
    private readonly pdf: PDFDocument,
    private readonly font: PDFFont,
    private readonly bold: PDFFont,
  ) {
    this.page = pdf.addPage(A4);
    this.y = A4[1] - MARGIN;
  }

  /** A new page when the next block would not fit above the footer. */
  private ensure(space: number) {
    if (this.y - space >= MARGIN + 30) return;
    this.page = this.pdf.addPage(A4);
    this.y = A4[1] - MARGIN;
  }

  text(value: string, options: { size?: number; bold?: boolean; x?: number } = {}) {
    const size = options.size ?? 10;
    this.ensure(size + 4);
    this.page.drawText(encodable(value), {
      x: options.x ?? MARGIN,
      y: this.y,
      size,
      font: options.bold ? this.bold : this.font,
    });
    if (options.x === undefined) this.y -= size + 8;
  }

  /** Columns at fixed offsets, drawn as one row. */
  row(cells: string[], offsets: number[], bold = false) {
    this.ensure(LINE);
    const top = this.y;
    cells.forEach((cell, index) => {
      this.page.drawText(encodable(cell), {
        x: MARGIN + offsets[index],
        y: top,
        size: 10,
        font: bold ? this.bold : this.font,
      });
    });
    this.y = top - LINE;
  }

  rule() {
    this.ensure(10);
    this.page.drawLine({
      start: { x: MARGIN, y: this.y },
      end: { x: A4[0] - MARGIN, y: this.y },
      thickness: 0.5,
      color: rgb(0.7, 0.7, 0.7),
    });
    this.y -= 14;
  }

  gap(space = 10) {
    this.y -= space;
  }

  /** Footers last, on every page — each drawn on its own page. */
  footers() {
    const pages = this.pdf.getPages();
    pages.forEach((page, index) => {
      page.drawText(encodable("Generated by HouseOS"), {
        x: MARGIN,
        y: MARGIN - 20,
        size: 8,
        font: this.font,
        color: rgb(0.5, 0.5, 0.5),
      });
      page.drawText(`Page ${index + 1} of ${pages.length}`, {
        x: A4[0] - MARGIN - 70,
        y: MARGIN - 20,
        size: 8,
        font: this.font,
        color: rgb(0.5, 0.5, 0.5),
      });
    });
  }
}

async function render(statement: SettlementStatement, houseName: string): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const sheet = new Sheet(pdf, font, bold);

  sheet.text("Settlement statement", { size: 18, bold: true });
  sheet.text(houseName, { size: 12 });
  sheet.text(statement.period, { size: 12 });
  sheet.rule();

  sheet.text("Summary", { size: 14, bold: true });
  sheet.text(`Total expenses: ${money(statement.totalExpensesPaise)}`);
  sheet.text(`Total fair share: ${money(statement.totalFairSharePaise)}`);
  sheet.text(
    statement.netsToZero
      ? "The month balances: every rupee owed is a rupee owed to somebody."
      : "This month does not balance. Ask an admin to reopen and close it again.",
  );
  sheet.gap();
  sheet.rule();

  const memberColumns = [0, 180, 290, 400];
  sheet.text("Member positions", { size: 14, bold: true });
  sheet.row(["Member", "Paid", "Fair share", "Net"], memberColumns, true);
  sheet.rule();
  for (const member of statement.members) {
    sheet.row(
      [
        member.name,
        money(member.paidPaise),
        money(member.fairSharePaise),
        money(member.netPaise),
      ],
      memberColumns,
    );
  }

  sheet.gap();
  sheet.rule();
  sheet.text("Payments", { size: 14, bold: true });

  if (statement.payments.length === 0) {
    // A month where nobody owes anybody is a real and unremarkable outcome.
    sheet.text("Nothing to settle: every member ended the month square.");
  } else {
    const paymentColumns = [0, 160, 320, 420];
    sheet.row(["From", "To", "Amount", "Status"], paymentColumns, true);
    sheet.rule();
    for (const payment of statement.payments) {
      sheet.row(
        [payment.fromName, payment.toName, money(payment.amountPaise), payment.status],
        paymentColumns,
      );
    }
  }

  sheet.footers();
  return pdf.save();
}
