import { NextResponse, type NextRequest } from "next/server";
import { createServerClient } from "@supabase/ssr";
import type { Database } from "@/lib/types/database";
import { supabaseAnonKey, supabaseUrl } from "./env";
import { contentSecurityPolicy, createNonce, cspHeaderName } from "@/lib/infra/http/csp";
import { WRITE_SCOPE, isCountedWrite, writeLimit } from "@/lib/infra/http/rate-limit";

/**
 * Routes reachable without a session. Everything else redirects to sign in.
 *
 * `/api/auth` is on the list because those endpoints ARE the way in — sign-up
 * and sign-in have no session yet by definition. The ones among them that do
 * need a caller, such as claiming a username, check for it themselves.
 */
const PUBLIC_PREFIXES = [
  "/signin",
  "/signup",
  "/auth",
  "/api/auth",
  // An invite link is opened by somebody who may have no account at all. The
  // landing page shows a Home's name, shape and size and nothing else, and the
  // request it leads to is authenticated (docs/05-API-SPEC.md section 2.1).
  "/join",
  "/api/join",
  "/offline",
  // Read before signing up, and by a store reviewer who has no account at all.
  "/legal",
  "/manifest.webmanifest",
  "/sw.js",
  /*
    The files a crawler, a chat app and a browser tab ask for before anybody
    signs in. Without these the proxy answered each one with a redirect to
    /signin, so `robots.txt` was an HTML login page, `sitemap.xml` was an HTML
    login page, and every link to this product unfurled a login page instead of
    its Open Graph card. All four are generated by `app/` routes and none of
    them names a household.
  */
  "/robots.txt",
  "/sitemap.xml",
  "/opengraph-image",
  "/twitter-image",
  "/icon.png",
  "/apple-icon.png",
  "/favicon.ico",
];

function isPublic(pathname: string): boolean {
  // The design-system pages render no household data and exist to be looked at
  // while signed out. The route itself 404s in production, so this only ever
  // matches on a developer's machine.
  if (process.env.NODE_ENV !== "production" && pathname.startsWith("/dev/")) return true;

  return PUBLIC_PREFIXES.some(
    (prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`),
  );
}

/**
 * Refreshes the Supabase session cookie on every request and keeps signed-out
 * visitors out of the app. This is convenience and correctness of navigation —
 * the security boundary is RLS, not this function.
 *
 * It is also where the Content-Security-Policy is minted, because a nonce has
 * to be per request and the proxy is the only thing that sees every one. The
 * policy itself, and the reasoning behind what it does and does not forbid, is
 * in `lib/infra/http/csp.ts`.
 */
export async function updateSession(request: NextRequest) {
  const nonce = createNonce();
  const policy = contentSecurityPolicy({
    nonce,
    dev: process.env.NODE_ENV !== "production",
    supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL,
    analyticsSrc: process.env.NEXT_PUBLIC_ANALYTICS_SRC,
  });
  const headerName = cspHeaderName(process.env.CSP_REPORT_ONLY === "1");

  /*
    The nonce reaches the renderer two ways, and it needs both. Next parses the
    `Content-Security-Policy` *request* header to stamp its own script tags;
    `x-nonce` is what the root layout reads to stamp the one script this app
    writes itself, the pre-paint theme script.

    A fresh copy of the request headers per call, rather than one taken at the
    top: `request.cookies.set` below rewrites the cookie header, and a snapshot
    made before that would send the old session downstream.
  */
  const forward = () => {
    const headers = new Headers(request.headers);
    headers.set("x-nonce", nonce);
    headers.set("Content-Security-Policy", policy);
    return headers;
  };

  const secured = <T extends NextResponse>(response: T): T => {
    response.headers.set(headerName, policy);
    return response;
  };

  let response = NextResponse.next({ request: { headers: forward() } });

  const supabase = createServerClient<Database>(supabaseUrl(), supabaseAnonKey(), {
    cookies: {
      getAll() {
        return request.cookies.getAll();
      },
      setAll(cookiesToSet) {
        for (const { name, value } of cookiesToSet) {
          request.cookies.set(name, value);
        }
        response = NextResponse.next({ request: { headers: forward() } });
        for (const { name, value, options } of cookiesToSet) {
          response.cookies.set(name, value, options);
        }
      },
    },
  });

  // getUser, not getSession: it revalidates the token with Supabase rather than
  // trusting a cookie the browser could have edited. An unreachable auth server
  // is treated as "not signed in" rather than a 500 on every route — the sign-in
  // page still has to render when the network is down.
  let user = null;
  try {
    const result = await supabase.auth.getUser();
    user = result.data.user;
  } catch (error) {
    console.warn("[proxy] could not reach Supabase auth", error);
  }

  const { pathname } = request.nextUrl;

  if (!user && !isPublic(pathname)) {
    /*
      An API request gets an answer, not a redirect.

      Every /api/* call from a signed-out caller used to be answered with a 307
      to /signin, so a `fetch` in a tab whose session had expired received an
      HTML login page. `response.json()` then threw, and the screen said "That
      did not work" — which is the one thing that had not happened. The person
      needed to be told they were signed out.

      The shape matches the rest of the API so the same client code reads it:
      `{ error: { code, message } }`, 401.
    */
    if (pathname.startsWith("/api/")) {
      return secured(
        NextResponse.json(
          {
            error: {
              code: "UNAUTHENTICATED",
              message: "You have been signed out. Sign in again to continue.",
            },
          },
          { status: 401 },
        ),
      );
    }

    const redirect = request.nextUrl.clone();
    redirect.pathname = "/signin";
    redirect.searchParams.set("next", pathname);
    return secured(NextResponse.redirect(redirect));
  }

  /*
    A signed-in member cannot hammer a write endpoint.

    Here rather than in each route, because there are ninety-odd of them and a
    limiter that covers eighty-nine is a limiter with a hole in it. The count
    lives in Postgres (migration 090) so that two instances of this server share
    one counter; an in-memory one would limit a fraction of the traffic and
    report that it had limited all of it.

    **It fails open.** If the database cannot be reached the request goes
    through: this is a defence against a loop, not an authorisation check, and
    the authorisation check is RLS, which is in the same database. Refusing
    every write because the counter is unavailable would turn a slow database
    into an outage.
  */
  if (user && isCountedWrite(request.method, pathname)) {
    const { limit, windowSeconds } = writeLimit();
    try {
      const { data, error } = await supabase.rpc("consume_rate_limit", {
        p_scope: WRITE_SCOPE,
        p_limit: limit,
        p_window_seconds: windowSeconds,
      });
      const verdict = data?.[0];
      if (!error && verdict && !verdict.allowed) {
        const response = NextResponse.json(
          {
            error: {
              code: "RATE_LIMITED",
              message: "Slow down a moment and try again",
            },
          },
          { status: 429 },
        );
        response.headers.set("Retry-After", String(verdict.retry_after_seconds));
        return secured(response);
      }
    } catch (error) {
      console.warn("[proxy] rate limit check failed open", error);
    }
  }

  if (user && (pathname === "/signin" || pathname === "/signup")) {
    const redirect = request.nextUrl.clone();
    redirect.pathname = "/homes";
    redirect.search = "";
    return secured(NextResponse.redirect(redirect));
  }

  return secured(response);
}
